// === eNode local config (GENERATED by eNode-install, DO NOT EDIT) ===
// This file is git-ignored. eNode-install writes the real host URL here.
// Keep the export shape matching config.js expectations.
export const PROXMOX_NODE_URL = '';
